#undef ISCONTACT_tempalte
#undef ISCONTACT_concept
#undef ISCONTACT_concept_inline
#undef ISCONTACT_concept_main
#undef OBJECT_operator_equal_concept
#undef OBJECT_operator_equal_with_concept_main
#undef OBJECT_operator_equal_with_concept
#undef OBJECT_operator_equal_with_concept_define
